aws-path: ~/.local/bin/aws
region: us-west-2
function-name: foo
zip-file: fileb://foo/build/foo.zip
role: arn:aws:iam::497270418792:role/Lambda-S3-Execution-Role
handler: src.lambda_function.lambda_handler
runtime: python3.6
profile: default
timeout: 10
memory-size: 1024
